import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'
import { subDays, addDays, startOfDay, endOfDay } from 'date-fns'

const prisma = new PrismaClient()

async function main() {
    console.log("🌱 Starting seed...")

    // 1. Create Users
    const password = 'password123'
    const hashedPassword = await bcrypt.hash(password, 10)

    const usersData = [
        { email: 'user@compass.com', name: 'Sean (Manager)', role: 'MANAGER', billableRate: 250, avatarUrl: "https://github.com/shadcn.png" },
        { email: 'sarah@compass.com', name: 'Sarah (Senior)', role: 'SENIOR', billableRate: 185, avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=100&h=100" },
        { email: 'mike@compass.com', name: 'Mike (Associate)', role: 'ASSOCIATE', billableRate: 125, avatarUrl: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&q=80&w=100&h=100" },
        { email: 'emily@compass.com', name: 'Emily (Associate)', role: 'ASSOCIATE', billableRate: 125, avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=100&h=100" },
    ]

    const users = []
    for (const u of usersData) {
        const user = await prisma.user.upsert({
            where: { email: u.email },
            update: { name: u.name, role: u.role, billableRate: u.billableRate, avatarUrl: u.avatarUrl },
            create: { ...u, password: hashedPassword },
        })
        users.push(user)
    }

    // 2. Create Projects
    const projectsData = [
        { name: "TechCorp Audit 2024", code: "TC-AUD-24", isBillable: true, billableRate: 200, managerRate: 300, seniorRate: 220, associateRate: 150 },
        { name: "NonProfit 990 Filing", code: "NP-990", isBillable: true, billableRate: 150 },
        { name: "Internal Operations", code: "INT-OPS", isBillable: false },
        { name: "Stark Industries Advisory", code: "SI-ADV", isBillable: true, billableRate: 400 },
        { name: "Mom & Pop Shop Bookkeeping", code: "MPS-BK", isBillable: true, billableRate: 100 },
    ]

    const projects = []
    for (const p of projectsData) {
        const project = await prisma.project.upsert({
            where: { code: p.code },
            update: {
                isBillable: p.isBillable,
                billableRate: p.billableRate,
                managerRate: p.managerRate,
                seniorRate: p.seniorRate,
                associateRate: p.associateRate
            },
            create: {
                ...p,
                description: `Project entity for ${p.name}`,
                users: { connect: users.map(u => ({ id: u.id })) }
            }
        })
        projects.push(project)
    }

    // 3. Create Task Templates (SOPs)
    const sopGroup = await prisma.taskTemplateGroup.create({
        data: {
            name: "Monthly Bookkeeping SOP",
            description: "Standard procedure for monthly client bookkeeping",
            templates: {
                create: [
                    { title: "Bank Reconciliation", priority: "P1", relativeDueDays: 5, assigneeRole: "ASSOCIATE", taskType: "Bookkeeping" },
                    { title: "Review Categorizations", priority: "P2", relativeDueDays: 7, assigneeRole: "SENIOR", taskType: "Review" },
                    { title: "Generate Monthly Reports", priority: "P2", relativeDueDays: 10, assigneeRole: "ASSOCIATE", taskType: "Reporting" },
                    { title: "Client Meeting", priority: "P1", relativeDueDays: 14, assigneeRole: "MANAGER", taskType: "Meeting" },
                ]
            }
        }
    })

    // 4. Generate Work Items (Tasks)
    const taskTitles = ["Q1 Financial Review", "Tax Prep", "Payroll Audit", "Strategy Meeting", "Client Onboarding", "Cleanup", "EOM Close"]
    const taskStatuses = ["OPEN", "IN_PROGRESS", "DONE"]
    const priorities = ["P1", "P2", "P3"]

    const workItems = []
    for (const project of projects) {
        for (let i = 0; i < 5; i++) {
            const assignee = users[Math.floor(Math.random() * users.length)]
            const status = taskStatuses[Math.floor(Math.random() * taskStatuses.length)]
            // Create some overdue tasks
            const isOverdue = Math.random() > 0.7
            const dueDate = isOverdue ? subDays(new Date(), Math.floor(Math.random() * 10)) : addDays(new Date(), Math.floor(Math.random() * 30))
            const completedAt = status === "DONE" ? subDays(new Date(), Math.floor(Math.random() * 5)) : null

            const task = await prisma.workItem.create({
                data: {
                    title: `${taskTitles[Math.floor(Math.random() * taskTitles.length)]} - ${project.code}`,
                    description: "Generated by seed script",
                    status,
                    priority: priorities[Math.floor(Math.random() * priorities.length)],
                    projectId: project.id,
                    assigneeId: assignee.id,
                    dueDate,
                    completedAt,
                    createdAt: subDays(new Date(), Math.floor(Math.random() * 60))
                }
            })
            workItems.push(task)
        }
    }

    // 5. Generate Time Entries (Last 30 Days)
    const today = new Date()
    for (let i = 0; i < 100; i++) {
        const user = users[Math.floor(Math.random() * users.length)]
        const project = projects[Math.floor(Math.random() * projects.length)]

        // 50% chance to link to a task
        const relevantTasks = workItems.filter(t => t.projectId === project.id)
        const task = Math.random() > 0.5 && relevantTasks.length > 0
            ? relevantTasks[Math.floor(Math.random() * relevantTasks.length)]
            : null

        const dateOffset = Math.floor(Math.random() * 30) // 0 to 30 days ago
        const entryDate = subDays(today, dateOffset)
        const duration = Math.floor(Math.random() * 4 * 3600) + 1800 // 0.5h to 4.5h in seconds

        await prisma.timeEntry.create({
            data: {
                userId: user.id,
                projectId: project.id,
                workItemId: task?.id,
                durationSeconds: duration,
                startedAt: startOfDay(entryDate), // Simplified start time
                notes: task ? `Worked on ${task.title}` : `General project work for ${project.name}`,
                isBillable: project.isBillable
            }
        })
    }

    console.log("✅ Seed completed!")
    console.log(`- ${users.length} Users`)
    console.log(`- ${projects.length} Projects`)
    console.log(`- ${workItems.length} Tasks`)
    console.log(`- ~100 Time Entries`)
}

main()
    .then(async () => {
        await prisma.$disconnect()
    })
    .catch(async (e) => {
        console.error(e)
        await prisma.$disconnect()
        process.exit(1)
    })
