
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
    console.log("Starting Verification...")

    // 1. Setup Users (Assuming seed-hierarchy.ts was run or users exist)
    const manager = await prisma.user.findFirst({ where: { role: 'MANAGER' } })
    const senior = await prisma.user.findFirst({ where: { role: 'SENIOR' } })
    const associate = await prisma.user.findFirst({ where: { role: 'ASSOCIATE' } })

    if (!manager || !senior || !associate) {
        console.error("Missing users. Please run seed-hierarchy.ts first or ensure users exist.")
        return
    }

    // 2. Setup Project
    const project = await prisma.project.create({
        data: {
            name: "Role Verification Project",
            code: "RVP" + Math.floor(Math.random() * 1000),
            managerId: manager.id,
            seniorId: senior.id,
            associateId: associate.id,
            users: {
                connect: [{ id: manager.id }, { id: senior.id }, { id: associate.id }]
            }
        }
    })
    console.log(`Created Project: ${project.name} (${project.code})`)
    console.log(`Manager: ${manager.name}, Senior: ${senior.name}, Associate: ${associate.name}`)

    // 3. Create Template Group with Role-Based Tasks
    const group = await prisma.taskTemplateGroup.create({
        data: {
            name: "Role Test Flow",
            templates: {
                create: [
                    { title: "Manager Sign-off", assigneeRole: "MANAGER", priority: "P1" },
                    { title: "Senior Review", assigneeRole: "SENIOR", priority: "P2" },
                    { title: "Associate Prep", assigneeRole: "ASSOCIATE", priority: "P2" },
                    { title: "Unassigned Task", priority: "P3" } // Should default to applier
                ]
            }
        },
        include: { templates: true }
    })
    console.log(`Created Template Group: ${group.name}`)

    // 4. Apply Template
    // We'll mimic the action logic here or we can call the action if we export it correctly, but script is safer with prisma direct
    // Re-implementing logic for verification script clarity
    const templates = group.templates
    const tasksData = templates.map(t => {
        let assigneeId = manager.id // Default to manager (as if they applied it)
        if (t.assigneeRole === 'MANAGER') assigneeId = manager.id
        if (t.assigneeRole === 'SENIOR') assigneeId = senior.id
        if (t.assigneeRole === 'ASSOCIATE') assigneeId = associate.id

        return {
            title: t.title,
            projectId: project.id,
            assigneeId,
            description: "Generated by script"
        }
    })

    await prisma.workItem.createMany({ data: tasksData })

    // 5. Verify
    const tasks = await prisma.workItem.findMany({
        where: { projectId: project.id },
        include: { assignee: true }
    })

    console.log("\n--- Verification Results ---")
    tasks.forEach(t => {
        console.log(`Task: "${t.title}" -> Assigned to: ${t.assignee?.name} (${t.assignee?.role})`)
    })

    // Cleanup
    // await prisma.project.delete({ where: { id: project.id } })
    // await prisma.taskTemplateGroup.delete({ where: { id: group.id } })
}

main()
    .catch((e) => {
        console.error(e)
        process.exit(1)
    })
    .finally(async () => {
        await prisma.$disconnect()
    })
